export const SIMPLE_ACTION = 'REACT_REDUX_STATERT_KIT/HOME/SIMPLE_ACTION';
export const GET_FACT_DATA = 'REACT_REDUX_STATERT_KIT/HOME/GET_FACT_DATA';
export const GET_FACT_DATA_SUCCESS = 'REACT_REDUX_STATERT_KIT/HOME/GET_FACT_DATA_SUCCESS';
export const GET_FACT_DATA_FAIL = 'REACT_REDUX_STATERT_KIT/HOME/GET_FACT_DATA_FAIL';
export const FAIL_DATA_LOAD_TEXT = 'Sorry!!!! Fail load data, please try again';
